run: yarn
	npm start

yarn: /usr/local/bin/yarn
/usr/local/bin/yarn:
	npm install -g yarn

install-routing:
	npm install @react-navigation/native

install-routing-expo-dependencies: install-routing
	expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view

install-routing-navigation-stack:
	npm install @react-navigation/stack
	 
install-dependencies-to-fix-ios-status-bar:
	expo install expo-constants

install-expo-mail-composer:
	expo install expo-mail-composer
